package dev.secondsun.chip8.test


import dev.secondsun.chip8.Chip8
import kotlin.test.BeforeTest
import kotlin.test.Test
import kotlin.test.assertEquals

import java.lang.reflect.Field
import java.util.Random

/**
 *
 * In E01 We set up the Chip-8 processor and implemented the basic arithmetic
 * opcodes. In this section we will implement bitwise opcodes.
 *
 * These include AND, OR, XOR, and shifts.
 *
 * In this tests we will initialize the registers to the following values : V0 =
 * 0x64 V1 = 0x27 V2 = 0x12 V3 = 0xAE V4 = 0xFF V5 = 0xB4 V6 = 0x42 VF = 0x25
 *
 * All other registers will be 0.
 *
 * Additionally we will be using reflection to control the random values
 * generated by java.
 *
 */
class E02BitwiseOpCodeTest {
    private lateinit var chip8: Chip8

    @BeforeTest
    fun setUp() {
        this.chip8 = Chip8()
        controlRandom()
        this.chip8.execute(0x6064)
        this.chip8.execute(0x6127)
        this.chip8.execute(0x6212)
        this.chip8.execute(0x63AE)
        this.chip8.execute(0x64FF)
        this.chip8.execute(0x65B4)
        this.chip8.execute(0x6642)
        this.chip8.execute(0x6F25)
    }


    /**
     * 8XY2	Set VX to VX & VY
     */
    @Test
    fun testAndOpCodes() {
        chip8.execute(0x8012) // v0 = 0x64 & 0x27
        assertEquals(36, chip8.v0)
        assertEquals(0x27, chip8.v1)

        chip8.execute(0x8232) // v2 = 0x12 & 0xAE
        assertEquals(2, chip8.v2)
        assertEquals(0xAE, chip8.v3)

        chip8.execute(0x8FE2) // 0x25 & 0x0
        assertEquals(0, chip8.vF)
    }

    /**
     * 8XY1	Set VX to VX | VY
     */
    @Test
    fun testOROpCodes() {
        chip8.execute(0x8011) // v0 = 0x64 | 0x27
        assertEquals(103, chip8.v0)
        assertEquals(0x27, chip8.v1)

        chip8.execute(0x8231) // v2 = 0x12 | 0xAE
        assertEquals(190, chip8.v2)
        assertEquals(0xAE, chip8.v3)

        chip8.execute(0x8FE1) // 0x25 | 0x0
        assertEquals(0x25, chip8.vF)
    }

    /**
     * 8XY3	Set VX to VX ^ VY
     */
    @Test
    fun testXOROpCodes() {
        chip8.execute(0x8013) // v0 = 0x64 ^ 0x27
        assertEquals(67, chip8.v0)
        assertEquals(0x27, chip8.v1)

        chip8.execute(0x8233) // v2 = 0x12 ^ 0xAE
        assertEquals(188, chip8.v2)
        assertEquals(0xAE, chip8.v3)

        chip8.execute(0x8FE3) // 0x25 ^ 0x0
        assertEquals(0x25, chip8.vF)
    }

    /**
     * 8XY6	Shift VX Right one place and store the result in VX. Also store the
     * lest significant bit in VF
     */
    @Test
    fun testShiftRight() {
        chip8.execute(0x8016) // v0 = 0x27 >> 1; xF = 0x1
        assertEquals(0x32, chip8.v0)
        assertEquals(0x0, chip8.vF)

        chip8.execute(0x8236) // v2 = 0xAE >> 1; VF = 0x0
        assertEquals(0x09, chip8.v2)
        assertEquals(0x0, chip8.vF)

        chip8.execute(0x8446) // V4 = 0xFF >> 1; VF = 0x1;
        assertEquals(127, chip8.v4)
        assertEquals(0x1, chip8.vF)
    }

    /**
     * 8XYE	Shift VX left one place and store the result in VX. Also store the
     * most significant bit in VF
     */
    @Test
    fun testShiftLeft() {
        chip8.execute(0x801E) // v0 = 0x27 << 1; xF = 0x1
        assertEquals(200, chip8.v0)
        assertEquals(0x0, chip8.vF)

        chip8.execute(0x823E) // v2 = 0xAE << 1; VF = 0x0
        assertEquals(36, chip8.v2)
        assertEquals(0x0, chip8.vF)

        chip8.execute(0x844E) // V4 = 0xFF << 1; VF = 0x1;
        assertEquals(254, chip8.v4)
        assertEquals(0x1, chip8.vF)
    }

    /**
     * CXNN Generate a Random number, mask it with NN and store the results in
     * Vx.
     */
    @Test
    fun testRandom() {
        //230, 198,153, 29
        chip8.execute(0xC1FF) // V1 = 230 & 0xFF
        assertEquals(230, chip8.v1)

        chip8.execute(0xC23E) // v2 = 198 & 0x3E
        assertEquals(6, chip8.v2)

        chip8.execute(0xC44E) // V4 = 153 & 0x4E
        assertEquals(8, chip8.v4)
    }

    private fun controlRandom() {
        try {
            val field: Field = chip8.javaClass.getDeclaredField("random")
            field.setAccessible(true)
            field.set(chip8, Random(42))
        } catch (ex: IllegalArgumentException) {
            throw RuntimeException(ex)
        } catch (ex: IllegalAccessException) {
            throw RuntimeException(ex)
        } catch (ex: NoSuchFieldException) {
            throw RuntimeException(ex)
        } catch (ex: SecurityException) {
            throw RuntimeException(ex)
        }
    }
}
