[versions]
agp = "8.7.3"
android-compileSdk = "35"
android-minSdk = "24"
android-targetSdk = "35"
androidx-activity = "1.10.1"
androidx-lifecycle = "2.9.1"
composeHotReload = "1.0.0-alpha11"
composeMultiplatform = "1.8.2"
filekit = "0.10.0-beta04"
kotlin = "2.2.0"
kotlinx-coroutines = "1.10.2"
compose-webview-multiplatform = "2.0.0"
slf4j = "1.7.32"
jna = "5.17.0"
jfa = "1.2.0"
oshi = "5.8.6"
versioncompare = "1.4.1"
jetbrains-annotations = "22.0.0"
junit = "5.10.2"
compose-components-splitpane = "1.9.0-beta01"

[libraries]
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlin-test-junit ={module = "org.jetbrains.kotlin:kotlin-test-junit5" , version.ref = "kotlin" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }
androidx-lifecycle-viewmodel = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel", version.ref = "androidx-lifecycle" }
androidx-lifecycle-viewmodel-compose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "androidx-lifecycle" }
androidx-lifecycle-runtimeCompose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-runtime-compose", version.ref = "androidx-lifecycle" }
kotlinx-coroutinesSwing = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-swing", version.ref = "kotlinx-coroutines" }
compose-webview-multiplatform   = {module = "io.github.kevinnzou:compose-webview-multiplatform", version.ref = "compose-webview-multiplatform"}
filekit-dialogs = { module = "io.github.vinceglb:filekit-dialogs", version.ref = "filekit" }
filekit-dialogs-compose = { module = "io.github.vinceglb:filekit-dialogs-compose", version.ref = "filekit" }
slf4j-api = { group = "org.slf4j", name = "slf4j-api", version.ref = "slf4j" }
jna-jpms = { group = "net.java.dev.jna", name = "jna-jpms", version.ref = "jna" }
jna-platform-jpms = { group = "net.java.dev.jna", name = "jna-platform-jpms", version.ref = "jna" }
compose-components-splitpane = {module="org.jetbrains.compose.components:components-splitpane", version.ref="compose-components-splitpane"}
jfa = { group = "de.jangassen", name = "jfa", version.ref = "jfa" }
oshi-core = { group = "com.github.oshi", name = "oshi-core", version.ref = "oshi" }
versioncompare = { group = "io.github.g00fy2", name = "versioncompare", version.ref = "versioncompare" }
jetbrains-annotations = { group = "org.jetbrains", name = "annotations", version.ref = "jetbrains-annotations" }
junit-jupiter-api = { group = "org.junit.jupiter", name = "junit-jupiter-api", version.ref = "junit" }
junit-jupiter-engine = { group = "org.junit.jupiter", name = "junit-jupiter-engine", version.ref = "junit" }
junit-jupiter-params = { group = "org.junit.jupiter", name = "junit-jupiter-params", version.ref = "junit" }


[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
composeHotReload = { id = "org.jetbrains.compose.hot-reload", version.ref = "composeHotReload" }
composeMultiplatform = { id = "org.jetbrains.compose", version.ref = "composeMultiplatform" }
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }